version: "3.8"

services:
  skyperollcall:
    image: skyperollcall
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/home/appuser
